export const SERVICES = [
  {
    id: 'asphalt',
    title: 'Asphalt Road Construction',
    description:
      'Hot-mix asphalt paving with DBM and BC layers, executed by our own batching plant and heavy paving fleet with fully safety-equipped crew (helmets, jackets, shoes) for durable, smooth surfaces.',
    image: '/services/road-construction-2.jpg',
    images: [
      '/services/road-construction-2.jpg',
      '/services/road-construction-1.jpg',
      '/services/road-construction-3.jpg',
      '/projects/town-park/08.jpg',
      '/projects/town-park/01.jpg',
      '/projects/provident-equinox/04.jpg',
      '/projects/provident-equinox/01.jpg',
      '/projects/ellegenza/01.jpg',
      '/projects/ellegenza/02.jpg',
      '/projects/kenso-hills/01.jpg',
      '/projects/oakshire/01.jpg',
    ],
  },
  {
    id: 'concrete',
    title: 'Concrete Road Work',
    description:
      'RCC / PQC concrete roads and pavements with precision expansion joints, reinforced subgrades, and smooth surface finishing designed for heavy industrial and residential traffic.',
    image: '/projects/site-49.jpg',
    images: [
      '/projects/site-49.jpg',
      '/projects/site-50.jpg',
      '/projects/site-10.jpg',
      '/projects/site-13.jpg',
      '/projects/site-14.jpg',
      '/projects/site-15.jpg',
      '/projects/site-16.jpg',
      '/projects/site-20.jpg',
      '/projects/site-22.jpg',
      '/projects/site-54.jpg',
      '/projects/kenso-hills/18.jpg',
    ],
  },
  {
    id: 'paver',
    title: 'Paver Road Works',
    description:
      'Interlocking heavy-duty paver blocks for township internal roads, footpaths, driveways, and parking areas with engineered sand bedding, edge kerb restraints, and plate compaction.',
    image: '/projects/kenso-hills/12.jpg',
    images: [
      '/projects/kenso-hills/12.jpg',
      '/projects/kenso-hills/11.jpg',
      '/projects/kenso-hills/13.jpg',
      '/projects/town-park/04.jpg',
      '/projects/ellegenza/03.jpg',
      '/projects/site-01.jpg',
      '/projects/site-04.jpg',
      '/projects/site-05.jpg',
      '/projects/site-06.jpg',
      '/projects/provident-equinox/08.jpg',
    ],
  },
  {
    id: 'infrastructure',
    title: 'Infrastructure Development',
    description:
      'Large-scale external infrastructure development including site grading, storm water drainage networks, RCC utility trenches, earthwork, and integrated road layouts.',
    image: '/projects/kenso-hills/07.jpg',
    images: [
      '/projects/kenso-hills/07.jpg',
      '/projects/site-02.jpg',
      '/projects/site-03.jpg',
      '/projects/site-12.jpg',
      '/projects/site-53.jpg',
      '/projects/kenso-hills/08.jpg',
      '/projects/town-park/07.jpg',
    ],
  },
  {
    id: 'hardscape',
    title: 'Hardscape Works',
    description:
      'External hardscape development - cast-in-situ and precast kerb works, paver installations, pedestrian walkways, landscaped plazas, and outdoor site finishing.',
    image: '/projects/kenso-hills/10.jpg',
    images: [
      '/projects/kenso-hills/10.jpg',
      '/projects/site-08.jpg',
      '/projects/site-27.jpg',
      '/projects/site-48.jpg',
      '/projects/site-07.jpg',
      '/projects/kenso-hills/09.jpg',
    ],
  },
  {
    id: 'external-civil',
    title: 'External Civil Works',
    description:
      'External civil construction - stone and RCC retaining walls, RCC box drains, compound walls, block masonry, plastering, and outdoor structural civil developments.',
    image: '/projects/site-35.jpg',
    images: [
      '/projects/site-35.jpg',
      '/projects/site-36.jpg',
      '/projects/site-37.jpg',
      '/projects/site-09.jpg',
      '/projects/site-11.jpg',
      '/projects/site-28.jpg',
      '/projects/site-38.jpg',
      '/projects/site-45.jpg',
      '/projects/site-58.jpg',
    ],
  },
]

export const MACHINERY = [
  {
    category: 'Road & Paving Equipment',
    items: [
      {
        name: 'Tar Paver Machines (Asphalt Pavers)',
        count: 6,
        specs: 'S.V.P Hi-Tech & Apollo Sensor Asphalt Paver Finishers for DBM & Bituminous Concrete',
        image: '/machinery/tar-paver.jpg',
      },
      {
        name: 'Road Rollers & Soil Compactors',
        count: 10,
        specs: 'HAMM HD 90 & 311 Heavy Vibratory Soil Compactors & Tandem Rollers',
        image: '/machinery/hamm-roller.jpg',
      },
      {
        name: 'JCB & Backhoe Loaders',
        count: 15,
        specs: 'CAT & JCB 3DX Heavy Excavator Loaders with Multi-Purpose Shovel Buckets',
        image: '/machinery/jcb-loader.jpg',
      },
      {
        name: 'Tandem Road Rollers Fleet (L&T 752)',
        count: 8,
        specs: 'L&T 752 & Ingersoll Rand Tandem Vibratory Road Compaction Fleet',
        image: '/machinery/rollers-fleet.jpg',
      },
    ],
  },
  {
    category: 'Asphalt & Mixing Plant Facilities',
    items: [
      {
        name: 'Asphalt Hot-Mix Batching Plants & Yard',
        count: 2,
        specs: 'Continuous Hot Mix Asphalt Batching Plant & Central Aggregate Stockpile Facility',
        image: '/machinery/paver-yard.jpg',
      },
      {
        name: 'Paver Finishers Lineup (Hopper Fleet)',
        count: 6,
        specs: 'Heavy-Duty Asphalt Paver Finishers with High-Capacity Feed Hoppers',
        image: '/machinery/pavers-lineup.jpg',
      },
    ],
  },
  {
    category: 'Heavy Material Transport Fleet',
    items: [
      {
        name: 'Heavy Tipper Trucks (SVP Fleet)',
        count: 22,
        specs: 'S.V.P Heavy Tipper Trucks for Hot Asphalt, GSB, WMM, Bitumen & Aggregates Transport',
        image: '/machinery/tipper-trucks.jpg',
      },
      {
        name: 'Site Compactors & Utility Units',
        count: 10,
        specs: 'Heavy Tandem Vibratory Compactors & Site Utility Equipment for Road Construction',
        image: '/machinery/rollers-fleet.jpg',
      },
    ],
  },
]

export const CLIENTS = [
  { id: 1, name: 'Assetz Property Group', sector: 'Real Estate Developer', projectCount: 3 },
  { id: 2, name: 'Puravankara Limited', sector: 'Real Estate Developer', projectCount: 2 },
  { id: 3, name: 'Provident Housing', sector: 'Real Estate Developer', projectCount: 1 },
  { id: 4, name: 'Nambiar Builders', sector: 'Real Estate Developer', projectCount: 3 },
  { id: 5, name: 'Sattva Group', sector: 'Real Estate Developer', projectCount: 2 },
  { id: 6, name: 'Shirasa Construction', sector: 'Infrastructure & Construction', projectCount: 1 },
  { id: 7, name: 'Sobha Limited', sector: 'Real Estate Developer', projectCount: 2 },
  { id: 8, name: 'Kalpataru International Pvt Ltd', sector: 'Real Estate Developer', projectCount: 1 },
]

export const PROJECTS = [
  // 5 Ongoing Projects
  {
    id: 1,
    title: 'Assetz The Secret Lake',
    client_id: 1,
    client: { id: 1, name: 'Assetz Property Group' },
    projectType: 'Infrastructure',
    status: 'Under Progress',
    location: 'Bengaluru, Karnataka',
    description:
      'Comprehensive external infrastructure, internal road networks, storm water drainage, RCC drains and paving works for Assetz The Secret Lake township.',
    startDate: '2024-05-10',
    imageUrl: '/projects/site-01.jpg',
    gallery: [
      '/projects/site-01.jpg',
      '/projects/site-02.jpg',
      '/projects/site-03.jpg',
      '/projects/site-04.jpg',
    ],
  },
  {
    id: 2,
    title: 'Provident Deansgate',
    client_id: 3,
    client: { id: 3, name: 'Provident Housing' },
    projectType: 'Road Work',
    status: 'Under Progress',
    location: 'IVC Road, Bengaluru, Karnataka',
    description:
      'External road development, asphalt paving, concrete approaches, and external civil infrastructure for Provident Deansgate development.',
    startDate: '2024-08-15',
    imageUrl: '/projects/site-05.jpg',
    gallery: [
      '/projects/site-05.jpg',
      '/projects/site-06.jpg',
      '/projects/site-07.jpg',
      '/projects/site-08.jpg',
      '/projects/site-09.jpg',
    ],
  },
  {
    id: 3,
    title: 'Nambiar District 25',
    client_id: 4,
    client: { id: 4, name: 'Nambiar Builders' },
    projectType: 'Infrastructure',
    status: 'Under Progress',
    location: 'Sarjapur Road, Bengaluru, Karnataka',
    description:
      'Large-scale township internal roads, concentric paver avenues, RCC retaining walls, storm water drain network, and asphalt road construction for Nambiar District 25.',
    startDate: '2024-09-01',
    imageUrl: '/projects/district-25/01.jpg',
    gallery: Array.from({ length: 35 }, (_, i) => `/projects/district-25/${String(i + 1).padStart(2, '0')}.jpg`),
  },
  {
    id: 4,
    title: 'Sattva - Shirasa Construction Pvt Ltd',
    client_id: 6,
    client: { id: 6, name: 'Sattva / Shirasa Construction' },
    projectType: 'External Civil',
    status: 'Under Progress',
    location: 'Bengaluru, Karnataka',
    description:
      'External civil works, retaining walls, RCC drains, concrete pavement and asphalt works for Sattva - Shirasa Construction project.',
    startDate: '2024-11-20',
    imageUrl: '/projects/site-20.jpg',
    gallery: [
      '/projects/site-20.jpg',
      '/projects/site-21.jpg',
      '/projects/site-22.jpg',
      '/projects/site-23.jpg',
      '/projects/site-24.jpg',
    ],
  },
  {
    id: 5,
    title: 'Nambiar Enterprises LLP - Nambiar Bannerghatta Bilwardahalli Ph-01',
    client_id: 4,
    client: { id: 4, name: 'Nambiar Enterprises LLP' },
    projectType: 'Road Work',
    status: 'Under Progress',
    location: 'Bannerghatta - Bilwardahalli, Bengaluru, Karnataka',
    description:
      'Phase 01 road infrastructure, paver installation, kerb works, site grading, and asphalt paving for Nambiar Bannerghatta development.',
    startDate: '2025-01-10',
    imageUrl: '/projects/site-28.jpg',
    gallery: [
      '/projects/site-28.jpg',
      '/projects/site-29.jpg',
      '/projects/site-30.jpg',
      '/projects/site-31.jpg',
      '/projects/site-32.jpg',
    ],
  },

  // 5 Completed Projects
  {
    id: 6,
    title: 'Puravankara Sounds of Water',
    client_id: 2,
    client: { id: 2, name: 'Puravankara' },
    projectType: 'Road Work',
    status: 'Completed',
    location: 'Bannerghatta Road, Bengaluru, Karnataka',
    description:
      'Premium internal asphalt road network, designer paver work, hardscape features and comprehensive drainage infrastructure.',
    startDate: '2023-01-15',
    imageUrl: '/projects/site-35.jpg',
    gallery: [
      '/projects/site-35.jpg',
      '/projects/site-36.jpg',
      '/projects/site-37.jpg',
      '/projects/site-38.jpg',
    ],
  },
  {
    id: 7,
    title: 'Sattva Green Groves',
    client_id: 5,
    client: { id: 5, name: 'Sattva Group' },
    projectType: 'Infrastructure',
    status: 'Completed',
    location: 'Nelamangala, Bengaluru, Karnataka',
    description:
      'Complete plotted layout infrastructure, asphalt roads, RCC drain network, retaining walls, and utility corridors.',
    startDate: '2023-04-10',
    imageUrl: '/projects/site-42.jpg',
    gallery: [
      '/projects/site-42.jpg',
      '/projects/site-43.jpg',
      '/projects/site-44.jpg',
      '/projects/site-45.jpg',
    ],
  },
  {
    id: 8,
    title: 'Sattva Bhumi',
    client_id: 5,
    client: { id: 5, name: 'Sattva Group' },
    projectType: 'Concrete',
    status: 'Completed',
    location: 'Bengaluru, Karnataka',
    description:
      'PQC concrete roads, heavy-duty asphalt main corridors, paver walkways, and external civil works.',
    startDate: '2023-08-01',
    imageUrl: '/projects/site-48.jpg',
    gallery: [
      '/projects/site-48.jpg',
      '/projects/site-49.jpg',
      '/projects/site-50.jpg',
      '/projects/site-51.jpg',
    ],
  },
  {
    id: 9,
    title: 'Assetz Marq',
    client_id: 1,
    client: { id: 1, name: 'Assetz Property Group' },
    projectType: 'Hardscape',
    status: 'Completed',
    location: 'Whitefield, Bengaluru, Karnataka',
    description:
      'High-specification internal asphalt roads, perimeter RCC drains, hardscaping, paver walkways, and external civil finishing.',
    startDate: '2023-10-05',
    imageUrl: '/projects/site-53.jpg',
    gallery: [
      '/projects/site-53.jpg',
      '/projects/site-54.jpg',
      '/projects/site-55.jpg',
      '/projects/site-56.jpg',
    ],
  },
  {
    id: 10,
    title: 'Assetz Bloom and Dell',
    client_id: 1,
    client: { id: 1, name: 'Assetz Property Group' },
    projectType: 'Paver',
    status: 'Completed',
    location: 'Whitefield, Bengaluru, Karnataka',
    description:
      'External civil infrastructure, asphalt roads, interlocking paver blocks, retaining structures, and landscape hardscape.',
    startDate: '2024-02-12',
    imageUrl: '/projects/site-58.jpg',
    gallery: [
      '/projects/site-58.jpg',
      '/projects/site-59.jpg',
      '/projects/site-60.jpg',
      '/projects/site-61.jpg',
    ],
  },
  {
    id: 11,
    title: 'Provident Equinox Ph-01',
    client_id: 8,
    client: { id: 8, name: 'Kalpataru International Pvt Ltd' },
    projectType: 'Infrastructure',
    status: 'Completed',
    location: 'Mysore Road, Bengaluru, Karnataka',
    description:
      'Asphalt road construction, DBM and BC paving, stormwater drainage networks, and external civil infrastructure works for Provident Equinox Phase 1.',
    startDate: '2023-03-15',
    imageUrl: '/projects/provident-equinox/01.jpg',
    gallery: Array.from({ length: 10 }, (_, i) => `/projects/provident-equinox/${String(i + 1).padStart(2, '0')}.jpg`),
  },
  {
    id: 12,
    title: 'Sobha Town Park',
    client_id: 7,
    client: { id: 7, name: 'Sobha Limited' },
    projectType: 'Infrastructure',
    status: 'Completed',
    location: 'Hosur Road / Attibele, Bengaluru, Karnataka',
    description:
      'Comprehensive township road network, RCC box drains, kerb works, asphalt paving and hardscape development for Sobha Town Park.',
    startDate: '2023-06-10',
    imageUrl: '/projects/town-park/01.jpg',
    gallery: Array.from({ length: 13 }, (_, i) => `/projects/town-park/${String(i + 1).padStart(2, '0')}.jpg`),
  },
  {
    id: 13,
    title: 'Purva Kenso Hills',
    client_id: 2,
    client: { id: 2, name: 'Puravankara Limited' },
    projectType: 'Infrastructure',
    status: 'Completed',
    location: 'IVC Road, Devanahalli, Bengaluru, Karnataka',
    description:
      'Plotted development external infrastructure, internal asphalt roads, heavy-duty paver blocks, stormwater RCC drains and retaining walls.',
    startDate: '2023-09-20',
    imageUrl: '/projects/kenso-hills/01.jpg',
    gallery: Array.from({ length: 39 }, (_, i) => `/projects/kenso-hills/${String(i + 1).padStart(2, '0')}.jpg`),
  },
  {
    id: 14,
    title: 'Sobha Oakshire',
    client_id: 7,
    client: { id: 7, name: 'Sobha Limited' },
    projectType: 'Road Work',
    status: 'Completed',
    location: 'IVC Road, Devanahalli, Bengaluru, Karnataka',
    description:
      'High-end villa township internal road construction, asphalt paving, kerbing, and comprehensive external civil infrastructure.',
    startDate: '2023-11-05',
    imageUrl: '/projects/oakshire/01.jpg',
    gallery: Array.from({ length: 7 }, (_, i) => `/projects/oakshire/${String(i + 1).padStart(2, '0')}.jpg`),
  },
  {
    id: 15,
    title: 'Nambiar Ellegenza Phase-01',
    client_id: 4,
    client: { id: 4, name: 'Nambiar Builders' },
    projectType: 'External Civil',
    status: 'Completed',
    location: 'Sarjapur Road / Chandapura, Bengaluru, Karnataka',
    description:
      'Internal road network, asphalt surfacing, designer interlocking paver blocks, RCC drains, and external civil works for luxury villa development.',
    startDate: '2024-01-18',
    imageUrl: '/projects/ellegenza/01.jpg',
    gallery: Array.from({ length: 23 }, (_, i) => `/projects/ellegenza/${String(i + 1).padStart(2, '0')}.jpg`),
  },
]

export const ALL_SITE_PHOTOS = Array.from({ length: 61 }, (_, i) => ({
  id: i + 1,
  src: `/projects/site-${String(i + 1).padStart(2, '0')}.jpg`,
  alt: `JGC Site Execution Photo ${i + 1}`,
}))
